COMPILE_DEPS = CORE_DEPS + CLI + [
    "//apps/ONOS_Integration_Service/api:onos-apps-ONOS_Integration_Service-api",
]

osgi_jar_with_tests(
    karaf_command_packages = ["com.maojianwei.onos.integrate.cli"],
    deps = COMPILE_DEPS,
)
