#COMPILE_DEPS = CORE_DEPS + [
#    "//apps/mao/api:onos-apps-mao-api",
#]
#
#osgi_jar_with_tests(
#    api_description = "REST API for Mao GUI",
#    api_package = "org.onosproject.mao.gui.rest",
#    api_title = "Mao api_title DHCP Server",
#    api_version = "1.0",
#    #    karaf_command_packages = ["org.onosproject.mao.gui.cli"],
#    test_deps = TEST_ADAPTERS,
#    #    web_context = "/onos/dhcp",
#    deps = COMPILE_DEPS,
#)
